// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cY4nGuqRRerez3gozW4dq3
// Component: cLj3qnxdQX
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_hands_on.module.css"; // plasmic-import: cY4nGuqRRerez3gozW4dq3/projectcss
import sty from "./PlasmicChapter4.module.css"; // plasmic-import: cLj3qnxdQX/css

export type PlasmicChapter4__VariantMembers = {};

export type PlasmicChapter4__VariantsArgs = {};
type VariantPropType = keyof PlasmicChapter4__VariantsArgs;
export const PlasmicChapter4__VariantProps = new Array<VariantPropType>();

export type PlasmicChapter4__ArgsType = {};
type ArgPropType = keyof PlasmicChapter4__ArgsType;
export const PlasmicChapter4__ArgProps = new Array<ArgPropType>();

export type PlasmicChapter4__OverridesType = {
  root?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  ul?: p.Flex<"ul">;
};

export interface DefaultChapter4Props {}

function PlasmicChapter4__RenderFunc(props: {
  variants: PlasmicChapter4__VariantsArgs;
  args: PlasmicChapter4__ArgsType;
  overrides: PlasmicChapter4__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vxxVf
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Chapter 4"}
              </h1>
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__wWhb
            )}
          >
            <React.Fragment>
              <React.Fragment>{""}</React.Fragment>
              <ul
                data-plasmic-name={"ul"}
                data-plasmic-override={overrides.ul}
                className={classNames(projectcss.all, projectcss.ul, sty.ul)}
              >
                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    projectcss.__wab_text,
                    sty.li__s0D3I
                  )}
                >
                  {"ボタンコンポーネントのテキストを可変にする"}
                </li>

                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    projectcss.__wab_text,
                    sty.li__gN1XF
                  )}
                >
                  {"ボタンの色を変えてみる"}
                </li>

                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    projectcss.__wab_text,
                    sty.li___2YYe0
                  )}
                >
                  {"ページを増やしてみる"}
                </li>

                <li
                  className={classNames(
                    projectcss.all,
                    projectcss.li,
                    projectcss.__wab_text,
                    sty.li__eRmO
                  )}
                >
                  {"ボタンをAタグに変えてリンクにしてみる"}
                </li>
              </ul>
              <React.Fragment>{""}</React.Fragment>
            </React.Fragment>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h1", "ul"],
  h1: ["h1"],
  ul: ["ul"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h1: "h1";
  ul: "ul";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChapter4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChapter4__VariantsArgs;
    args?: PlasmicChapter4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChapter4__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChapter4__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChapter4__ArgProps,
      internalVariantPropNames: PlasmicChapter4__VariantProps
    });

    return PlasmicChapter4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChapter4";
  } else {
    func.displayName = `PlasmicChapter4.${nodeName}`;
  }
  return func;
}

export const PlasmicChapter4 = Object.assign(
  // Top-level PlasmicChapter4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h1: makeNodeComponent("h1"),
    ul: makeNodeComponent("ul"),

    // Metadata about props expected for PlasmicChapter4
    internalVariantProps: PlasmicChapter4__VariantProps,
    internalArgProps: PlasmicChapter4__ArgProps
  }
);

export default PlasmicChapter4;
/* prettier-ignore-end */
